version: 0.0
os: linux
files:
  - source: /
    destination: /home/manage/my-manage-tool/
hooks:
  ApplicationStop:
    - location: scripts/stop_server.sh
      timeout: 300
  AfterInstall:
    - location: scripts/setup.sh
      timeout: 300
      runas: manage
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 300
