version: '3'
services:
  nginx:
    image: nginx:1.15.6
    container_name: nginx-my_manage_tool
    depends_on:
      - app
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./public:/var/www/html/public:cached
  app:
    build: ./docker/app
    container_name: app-my_manage_tool
    links:
      - mysql
    depends_on:
      - app-build
    volumes:
      - .:/var/www/html:cached
  app-build:
    build: ./docker/app
    container_name: app-build-my_manage_tool
    volumes:
      - ./:/var/www/html:cached
    command: /bin/bash -c 'composer install && if [ ! -e .env ]; then cp .env.local .env; fi && php artisan key:generate && php artisan jwt:secret && php artisan migrate && chmod -R 777 storage'
    links:
      - mysql
  mysql:
    image: mysql:5.7
    container_name: mysql-my_manage_tool
    environment:
      MYSQL_DATABASE: my_manage_tool
      MYSQL_USER: my_manage_tool
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
  https-portal:
    image: steveltn/https-portal:1
    container_name: https_portal-my_manage_tool
    ports:
      - "80:80"
      - "443:443"
    tty: true
    restart: always
    volumes:
      - ./docker/https-portal/cert:/var/lib/https-portal
    environment:
      DOMAINS: 'localhost -> http://nginx-my_manage_tool'
      STAGE: 'local'
    links:
      - app
volumes:
  mysql-data:
